### ISSUE TITLE
Android Mobile Device/Tablet required for this feature testing

### ISSUE THREAD

**Issue by citizen-kane** [nikraina/CSC510-Group-M#21]
This feature is unable to be tested via the emulator.
An android device (mobile/tablet) is required for the same.

Test Case:
When at the app home screen you press on the "My Location" button on the top-right corner, the map should move to your current location.

**Comment by citizen-kane** [comment]
After the last commit, where current location is calculated programatically, the emulator shows that the device is unable to connect when the current location button is clicked.
This needs to be confirmed via a device

**Comment by eggman89** [comment]
Let's do it with my device today. It's running on Marshmellow.

**Comment by citizen-kane** [comment]
Confirmed on an android Tablet, the app is working correctly.
