### ISSUE TITLE
Find good source of training guide in android.

### ISSUE THREAD

**Issue by akhan7** [nikraina/CSC510-Group-M#6]

**Comment by eggman89** [comment]
There are few good ones on Udemy. For example:
https://www.udemy.com/learn-android-programming-from-scratch-beta/

**Comment by citizen-kane** [comment]
Lynda.com provides a good course on Android Dev - It also helps with learning how to use Google Map APIs with it. You can create an account with a 10-day free trial run for the same.
Let us know if you find something good yourself.

**Comment by nikraina** [comment]
This seems redundant at this time, already developed the stuff, so guess we are quite familiar with Android :package:
