### ISSUE TITLE
Integrate Google Maps with the app

### ISSUE THREAD

**Issue by citizen-kane** [nikraina/CSC510-Group-M#9]
Basic map created at branch 'kagarwa'
To integrate google maps with the basic app

**Comment by eggman89** [comment]
Let's get the API key from here:
https://console.developers.google.com/flows/enableapi?apiid=maps_android_backend&keyType=CLIENT_SIDE_ANDROID&reusekey=true&pli=1

**Comment by nikraina** [comment]
this is done with last commit
